# Generated by Django 3.2.8 on 2021-11-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentsmodel',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='apartmentsmodel',
            name='check_out',
            field=models.DateField(),
        ),
    ]
