# Generated by Django 3.2.8 on 2021-11-06 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentsmodel',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='profile.profilemodel'),
        ),
    ]
