# Generated by Django 3.2.8 on 2021-10-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('max_speed_km_h', models.IntegerField()),
                ('lifting_tones', models.IntegerField()),
                ('wingspan_meters', models.IntegerField()),
            ],
            options={
                'db_table': 'aircrafts',
            },
        ),
        migrations.DeleteModel(
            name='ComputerModel',
        ),
    ]
